name: ci

on:
  pull_request:
    branches: [master]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.4"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Echo go version
        run: go version
